[package]
name = "zotera_actix"
version = "0.0.1"
edition = "2021"
authors = ["Lucas Nørgård"]
license = "MIT"
repository = "https://github.com/zotera/zotera"
description = "Actix integration for Zotera"

[dependencies]
actix-web = "4"
tokio = { version = "1.0", features = ["full"] }
