[workspace]
members = [
  "crates/zotera",
  "crates/zotera-server",
  "crates/config",
  "crates/zotera-cli",

  # Integrations
  "crates/integrations/zotera-actix",
  "crates/integrations/zotera-axum",

  # Examples
  "examples/actix"
]
