/*
 * This file is automatically generated.
 * Run 'pnpm run update:default-config' to update.
 */
import type { OmitSafe, ZoteraConfig } from '@zotera/types';

export const DEFAULT_CONFIGURATION_OBJECT: OmitSafe<ZoteraConfig, '__location'> = {
  pluginDir: './plugins',
  allowUnscopedPlugins: true,
  web: {
    title: 'Zotera Web',
    footer: {
      message: 'Powered by Zotera',
      copyright: 'Copyright © 2022'
    }
  },
  auth: {
    allowAnonymousDownload: true
  },
  logging: {
    type: 'stdout',
    level: 'info'
  },
  storage: {
    location: './storage'
  }
};
