pluginDir: ./plugins

# disabling this, will allow unscoped plugins to be loaded.
allowUnscopedPlugins: true

web:
  title: Zotera Web
  footer:
    message: Powered by Zotera
    copyright: Copyright © 2022

auth:
  allowAnonymousDownload: true
  # provider: github-oauth
  # Change to HTPasswd Algorithm (brcypt, sha256, sha512)
  algorithm: bcrypt

logging:
  type: stdout
  level: info

storage:
  # Default provider is local storage.
  # provider: <provider>
  location: ./storage
