/*
* This file is automatically generated.
* Run 'pnpm run update:dep-versions' to update.
*/

// This needs to be exported because it's used in update-versions.ts script.
export const depVersions: Record<string, string> = {
  "esbuild": "0.15.5",
  "@zotera/types": "0.0.1",
  "vitest": "0.22.1",
  "typescript": "4.8.2"
};