/*
 * This file is automatically generated.
 * Run 'pnpm run update:dep-versions' to update.
 */

// This needs to be exported because it's used in update-versions.ts script.
export const depVersions: Record<string, string> = {
  rollup: '2.78.0',
  vitest: '0.21.1',
  typescript: '4.7.4',
  tslib: '2.4.0',
  '@zotera/types': '0.0.1',
  '@rollup/plugin-node-resolve': '13.3.0',
  '@rollup/plugin-commonjs': '22.0.2',
  '@rollup/plugin-typescript': '8.3.4'
};
