import { promises as fs } from 'fs';
import yaml from 'js-yaml';

const command = 'pnpm run update:default-config';

const BANNER = `/*
* This file is automatically generated.
* Run '${command}' to update.
*/`;

async function run() {
  console.log('DEFAULT CONFIGURATION BUILDER');
  let contents: any = {};
  try {
    contents = yaml.load(await fs.readFile('./packages/config/src/configs/default.yaml', 'utf8'));
  } catch (e) {
    console.log(e);
  }

  fs.writeFile(
    './packages/config/src/configs/default.ts',
    `${BANNER}\n\nimport type { OmitSafe, ZoteraConfig } from '@zotera/types';\n\nexport const DEFAULT_CONFIGURATION_OBJECT: OmitSafe<ZoteraConfig, '__location'> = ${JSON.stringify(
      contents,
      null,
      2
    )};`
  );
}

run();
