[package]
name = "zotera_core"
version = "0.0.1"
edition = "2021"
authors = ["Lucas Nørgård"]
license = "MIT"
repository = "https://github.com/zotera/zotera"
description = "Zotera Core"

[dependencies]
zotera_config = { path = "../config" }
